[package]
name = "mage_gojo_blog"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = "0.7.1"
dioxus-ssr = "0.7.1"
actix-web = "4"
actix-files = "0.6.9"
clap = { version = "4", features = ["derive"] }
log="0.4.19"
env_logger="0.11.8"
futures-util="0.3.25"
